name: Weather Data Pipeline Workflow

permissions:
  contents: write  # Needed for pushing commits

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'  # Every 5 minutes (minimum allowed by GitHub)

jobs:
  run-weather-pipeline:
    name: Run Weather Pipeline
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout repository content
    - name: Checkout repo content
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
        cache: 'pip'

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt

    # Step 4: Run weather data pipeline
    - name: Run weather data pipeline
      run: |
        set -e
        python data_pipeline.py
    
    # Step 5: Check for changes and commit
    - name: Check for changes and commit
      run: |
        git config --local user.name 'github-actions[bot]'
        git config --local user.email 'github-actions[bot]@users.noreply.github.com'
        git add .
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Automated weather data update - $(date '+%Y-%m-%d %H:%M:%S')"
          git push origin main
        fi
