name: Toronto Weather Pipeline

permissions:
  contents: write

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: '*/10 * * * *'  # Every 10 minutes - more reliable

jobs:
  collect-weather:
    name: Collect Toronto Weather Data
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
        cache: 'pip'

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run weather pipeline
      run: |
        set -e
        python data_pipeline.py

    - name: Commit weather data
      run: |
        git config --local user.name 'github-actions[bot]'
        git config --local user.email 'github-actions[bot]@users.noreply.github.com'
        git add .
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Weather data update - $(date '+%Y-%m-%d %H:%M:%S')"
          git push origin main
        fi
